### ISSUE TITLE
Huge map? 

### ISSUE THREAD

**Issue by igabesz** [igabesz/realtime-game-ts#34]
Can we use a very big, or even limitless map in Phaser? Where only a part of the map is visible.

**Comment by igabesz** [comment]
@annakolozsvari What were the last conclusions about this issue?

**Comment by annakolozsvari** [comment]
tldr: We'll use a very big map.

We could only use a limitless map in a 1-player game (because then we'd
really be moving the world, not the player). We can't do that in
multiplayer, because 2 players could go in the opposite direction and which
one would the world bounds follow?
So for now we'll be using a huge map, letting the coordinates go until we
run out of memory or overflow (which is quite far). Later we'll implement
some kind of boundaries, like warnings that you're too far, possibly
decreasing the ship's health.

**Comment by igabesz** [comment]
Ok, seems good! Boundaries or health decrease will be another issue.

**Comment by annakolozsvari** [comment]
We decided that the server specifies the world bounds - map size can be different for different rooms. The default size is quite big, and if a ship approaches the verge, it starts getting damaged. Ships bounce back from the bounds (if they can reach it before dying), projectiles get destroyed when they leave the world.

**Comment by annakolozsvari** [comment]
(All this implemented on server and client too)
